version: '3.8'

services:
  autoiso:
    build: .
    container_name: autoiso
    restart: unless-stopped
    ports:
      - "5123:5000"
    environment:
      - TZ=Asia/Shanghai
      - DB_PATH=/data/autoiso.db
      - OUTPUT_DIR=/output
    volumes:
      - ./data:/data
      # 精确挂载具体的子文件夹，并保持与 qB 容器内的绝对路径一致，ro 表示只读保护原盘
      - /volume1/Downloads/封装前:/Downloads/封装前:ro 
      # 跨盘输出，极大提升封装 I/O 速度
      - /volume2/Movie/封装后:/output
      # 映射 cd2 的本地路径
      - /volume3/CloudNAS:/CloudNAS:rslave